[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CuArrays = "3a865a2d-5b23-5a0f-bc46-62713ec82fae"
CuYao = "b48ca7a8-dd42-11e8-2b8e-1b7706800275"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"
